apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: emoji-config
  namespace: flux-system
spec:
  interval: 10m
  url: oci://zot.jeremyrickard.com/kubecon/manifests/emojivoting
  ref:
    tag: latest
  verify:
    provider: notation
    secretRef:
      name: notation-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emoji-config
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: emoji
  prune: true
  sourceRef:
    kind: OCIRepository
    name: emoji-config
  path: ./