apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: check-image-notary
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: verify-signature-notary
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - type: Notary
        imageReferences:
        - "*"
        attestors:
        - count: 1
          entries:
          - certificates:
              cert: |-
                -----BEGIN CERTIFICATE-----
                MIIFoTCCA4mgAwIBAgIQVbah+0b5SbOB6nI1N8giDDANBgkqhkiG9w0BAQsFADBd
                MQswCQYDVQQGEwJVSzEPMA0GA1UECBMGTG9uZG9uMQ8wDQYDVQQHEwZMb25kb24x
                EDAOBgNVBAoTB2t1YmVjb24xGjAYBgNVBAMTEWplcmVteXJpY2thcmQuY29tMB4X
                DTI1MDMyOTE4NDAxNFoXDTI2MDMyOTE4NTAxNFowXTELMAkGA1UEBhMCVUsxDzAN
                BgNVBAgTBkxvbmRvbjEPMA0GA1UEBxMGTG9uZG9uMRAwDgYDVQQKEwdrdWJlY29u
                MRowGAYDVQQDExFqZXJlbXlyaWNrYXJkLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQAD
                ggIPADCCAgoCggIBAMJh4gQLG085sUjTdrcAYvtC717nP7LaJ8zBhavb/sqRRwxT
                vDJshnULnqrpuTXwITwFPQaVm3ldH6M95qSUeBSVRYSAPbcOFuSlnMfmiTuiailC
                snuUtHMoWh/A3/WNbwivo8rsKExWm5Aoz1i9MW+DBV9DH4K9eEsAO2hXqkDfXbhs
                cKBWXS+xSCgIgVblt9Pzeh7ch5dDTCxJEEItUIiMayjiEom6BhvBlHCma8wJkACJ
                6DySPW3BQSa3Ja8BatB2n+fcHDbjslb+k4HkWtj22XYIxCkd18sSgVRpNsIjcAl2
                O0jzlIFZhL763f16SUwdpwCuRltgX9ZIW1Je//90QyvBv+wnnixIVzPpYGrrtwse
                QVwXaYSzP6eB9uLhS22h0YKYFzoXywoGuT14w4Lioq3tV6OuJbuu9Y/YhwzoPP2g
                SJAU6WB1dOVN/sa4wT99nQcA8vjNvLgeBHehBxWIHnvtOEtwbEqf7XI751XJcGfd
                SjZSVld5QvGRto/6QAyBJ0VdhMszmlEK/p3c7OFuZ0uyqX14IFCD1gbURKch+Rtv
                aKOgjc8v3v1t5szWTvIjsCXyJouO9NO1ZGE9su4F5XsIfkQiYFP2eLDSlgtn8ZA1
                8jT6YvijcOjjkRQSQQr17Np+hriWBu3eRaC0rJivW9+dwA/EKMyQB9k04hD1AgMB
                AAGjXTBbMA4GA1UdDwEB/wQEAwIHgDAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFABF
                iVlTM3C52p+dV9x5HGR80vggMB0GA1UdDgQWBBQARYlZUzNwudqfnVfceRxkfNL4
                IDANBgkqhkiG9w0BAQsFAAOCAgEAeIqHCopg3TVwlR+ZVCtitS9u4M2UOdICygSy
                +RHuI8WYKwhQqDI7E7cMuWVV8V+duspvpJsGpGr5gobm41B7/63nXf05Bxkr5Ht1
                yx/ZoH3YC6aTgD1HkQPXmyli+tiASGqF9du6z8AVPCdkc53sd53/3H9cdiKuxGR0
                LHtvNigkqje3k+XQeLUxlJgNx5bILHNncCmZ5PNoZCz+a3/Fx2PbsifHUQsbnjnl
                qaaA3jEVmdA5ySZL3jcfNnVHsjb+3Gp3PvmvdF9FbtTmRKROc8ZuCMUWfhT2WOzd
                XmO4ZKqiU+zhInijyTImt/oNr3WVlLX0IRUR47YNkG2K7xrC42og83dZAZMfekG0
                HBTILlIwtHPsg1IeUMw7xraRIKhGeInB2iCPo1JhtHTGhbIA97d6aV1dZYX6Ull2
                BBN7k18RhMm7u7Gm62s2qTqlxq1v/yrl8BHfUhfqmxZPm8kqtZshMOYib3dMa4gX
                xb68qL+GMt9TzG2WlDB1ePL3PG6cXabNcTeMtrVUjtSiY5sWdLglHVhwX/aF7gOf
                GGQR5iLDuKPF6fzSwHyA1yQyJGMQ4XOQowl//g+RZim3cTPIjdS9EW5WPlhnZAG0
                qW0n2tER16k6ukHutkG6FkT005/DqgfYrHjl7Qj7RNSYAtk+TUl27ap6MfbXbfB/
                dnl8TCA=
                -----END CERTIFICATE-----               